name: Build & Test

on:
  push:
    branches: [ '1.20.1-1.10.0-greasy' ]

env:
  OUTPUT_JAR_FILE: 'Origins-1.20.1-1.10.0.jar'

jobs:
  build:
    name: 'Build lib & main JAR'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Run custom build script
        run: ./build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTPUT_JAR_FILE }}
          path: build/libs/${{ env.OUTPUT_JAR_FILE }}
